app/__init__.py
from flask import Flask
from flask_mysqldb import MySQL
from app.blueprints.auth.routes import auth_bp
from app.blueprints.dashboard.routes import dashboard_bp
from config import Config

mysql = MySQL()  # instancia global

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Configurar MySQL
    app.config['MYSQL_USER'] = 'root'
    app.config['MYSQL_PASSWORD'] = ''
    app.config['MYSQL_HOST'] = 'localhost'
    app.config['MYSQL_DB'] = 'tourism'
    app.config['MYSQL_PORT'] = 3306

    mysql.init_app(app)

    app.secret_key = Config.SECRET_KEY

    app.register_blueprint(dashboard_bp)
    app.register_blueprint(auth_bp)

    return app

app/blueprints/dashboard/__init__.py
from flask import Flask
from app.blueprints.auth.routes import auth_bp
from app.blueprints.dashboard.routes import dashboard_bp


def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = '$2a$10$kjPH5qzt5aYGcmnK3TYaD.7infnWlLTlBdrV/0Ak5zpOhoOlUQ8eS'
    app.config['JSONBIN_URL'] = 'https://api.jsonbin.io/v3/b/6719dadce41b4d34e447e513'

    app.register_blueprint(dashboard_bp)
    app.register_blueprint(auth_bp)
    app.register_blueprint(dashboard_bp)

    return app

app/blueprints/dashboard/routes.py
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect,current_app
import requests

from flask import render_template

from config import HEADEARS, JSONBIN_URL_DESTINOS
import mysql.connector 

dashboard_bp = Blueprint('dashboard', __name__)

@dashboard_bp.route('/')
def dashboard():
    # utiliza api de noticias
    api_key = 'aee10bfb3de5452bbef0f575e9389a9f'
    url = f'https://newsapi.org/v2/everything?q=turismo&language=es&pageSize=2&apiKey={api_key}'
    response = requests.get(url)
    noticias = response.json().get('articles', [])
    return render_template('dashboard/nosotros.html', noticias=noticias)
   

@dashboard_bp.route('/destinos')
def dashboarddestinos():
   return render_template('dashboard/destinos.html')


@dashboard_bp.route('/paquetes')
def dashboardpaquetes():
    response = requests.get(JSONBIN_URL_DESTINOS,headers=HEADEARS)
    if response.status_code == 200:
        data = response.json() 
        paquetes = data.get('record', []) 
        return render_template('dashboard/paquetes.html', paquetes= paquetes)  
    else:
        return jsonify({"error": "Error al cargar los datos."}), response.status_code
    
@dashboard_bp.app_template_filter("format_price")
def format_price(value):
    return "{:,.2f}".format(value).replace(",", "X").replace(".", ",").replace("X", ".")



@dashboard_bp.route('/listareserva', methods=['GET', 'POST'])
def dashboardlistareserva():
    try:
        connection = mysql.connector.connect(
            host='localhost',           
            user='root',                
            password='',               
            database='tourism'          
        )
        cursor = connection.cursor()

       
        sql = "SELECT id, nombre, email, nombre_destino, fecha_reserva, numero_personas, precio_total, imagen FROM reservas"
        cursor.execute(sql)
        reservas = cursor.fetchall()  # obtenemos todas las filas de resultados

        return render_template('dashboard/listareserva.html', reservas=reservas)

    except mysql.connector.Error as e:
        flash(f'Error al cargar las reservas: {e}', 'danger')
        return render_template('dashboard/listareserva.html')

    finally:
        # cerrar 
        cursor.close()
        connection.close()



@dashboard_bp.route('/reserva', methods=['GET', 'POST'])
def dashboardreserva():
    if request.method == 'POST':
        nombre = request.form.get('nombre')
        email = request.form.get('email')
        paquete_id_str = request.form.get('paquete_id')

        if not paquete_id_str:
            flash("No se recibió el ID del paquete.", "danger")
            return redirect(url_for('dashboard.dashboardpaquetes'))

        paquete_id = int(paquete_id_str)
        fecha_reserva = request.form.get('fecha_reserva')
        numero_personas = int(request.form.get('numero_personas'))

        response = requests.get(JSONBIN_URL_DESTINOS, headers=HEADEARS)
        paquetes = response.json()['record']

        paquete = next((p for p in paquetes if p["id"] == paquete_id), None)
        if not paquete:
            flash("Paquete no encontrado.", "danger")
            return redirect(url_for('dashboard.dashboardpaquetes'))

        nombre_destino = paquete["destino"]
        duracion = paquete["duracion"]
        mes = paquete["mes"]
        incluye = ", ".join(paquete["incluye"])
        precio_por_persona = float(paquete["precio_por_persona"])
        imagen = paquete["imagen"]
        precio_total = numero_personas * precio_por_persona

        try:
            connection = mysql.connector.connect(
                host='localhost',
                user='root',
                password='',
                database='tourism'
            )
            cursor = connection.cursor()

            sql = """
            INSERT INTO reservas (
                nombre, email, paquete_id, nombre_destino, duracion, mes, incluye,
                fecha_reserva, numero_personas, precio_total, imagen
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            cursor.execute(sql, (
                nombre, email, paquete_id, nombre_destino, duracion, mes, incluye,
                fecha_reserva, numero_personas, precio_total, imagen
            ))
            connection.commit()
            flash('Reserva creada exitosamente.', 'success')
        except mysql.connector.Error as e:
            connection.rollback()
            flash(f'Error al guardar reserva: {e}', 'danger')
        finally:
            cursor.close()
            connection.close()

        return redirect(url_for('dashboard.dashboardlistareserva'))

    # GET - mostrar formulario con ID del paquete
    paquete_id = request.args.get('paquete_id', type=int)
    if not paquete_id:
        flash("No se especificó un paquete.", "danger")
        return redirect(url_for('dashboard.dashboardpaquetes'))

    return render_template('dashboard/reserva.html', paquete_id=paquete_id)

@dashboard_bp.route('/eliminar_reserva/<int:id>', methods=['POST'])
def eliminar_reserva(id):
    try:
        
        connection = mysql.connector.connect(
            host='localhost',
            user='root',
            password='',
            database='tourism'
        )
        cursor = connection.cursor()

        
        sql = "DELETE FROM reservas WHERE id = %s"
        cursor.execute(sql, (id,))
        connection.commit()

        flash('Reserva eliminada exitosamente.', 'success')
    except mysql.connector.Error as e:
        flash(f'Error al eliminar la reserva: {e}', 'danger')
    finally:
        cursor.close()
        connection.close()

    return redirect(url_for('dashboard.dashboardlistareserva'))
    

    
@dashboard_bp.route('/test_mysql')
def test_mysql():
    import MySQLdb
    try:
        conn = MySQLdb.connect(
            host="localhost",
            user="root",
            passwd="",
            db="tourism"
        )
        cursor = conn.cursor()
        cursor.execute("SELECT 1")
        conn.close()
        return "Conexión exitosa a MySQL"
    except Exception as e:
        return f"Error al conectar a MySQL: {str(e)}", 500

app/templates/dashboard/destinos.html
{% extends 'layoutDashboard.html' %}

<!--  {% block title %}destinos{% endblock %} -->

{% block content %}
<h1 class="text-center text-primary fw-bold mb-4 text-success shadow-sm ">¡Vive Experiencias Inolvidables!</h1>
<div class="containerGalery">
    <div class="slider-wrapper">
        <button id="prev-slide" class="slide-button material-symbols-rounded bi bi-caret-left"></button>
        <div class="grid-container">
            <div class="grid-item">
                <img src="../static/img/naturaleza.jpg" alt="">
                <div class="text-overlay">Naturaleza y Turismo</div>
            </div>
            <div class="grid-item">
                <img src="../static/img/gastronomia.webp" alt="">
                <div class="text-overlay">Gastronomía</div>
            </div>
            <div class="grid-item">
                <img src="../static/img/cultura.jpg" alt="">
                <div class="text-overlay">Cultura</div>
            </div>
            <div class="grid-item">
                <img src="../static/img/playas.webp" alt="">
                <div class="text-overlay">Playas</div>
            </div>
        </div>
        
        <button id="next-slide" class="slide-button material-symbols-rounded bi bi-caret-right"></button>
    </div>
    <div class="slider-scrollbar">
        <div class="scrollbar-track">
            <div class="scrollbar-thumb"></div>
        </div>
    </div>
</div>

<h2 class="text-center text-uppercase text-success fw-semibold mb-3 shadow-sm  mt-4"
 >Conoce los Destinos</h2>

<div class="container-destinos">
    
<div class="card">
    <img src="../static/img/cordoba.jpg" alt="bahiaHawai">
    <div class="text">Córdoba</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
<div class="card">
    <img src="../static/img/bariloche.jpg" alt="bahiaHawai">
    <div class="text">Bariloche</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
<div class="card">
    <img src="../static/img/talampaya_laRioja.jpg" alt="bahiaHawai">
    <div class="text">La Rioja</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
</div>


<div class="container-destinos">
<div class="card">
    <img src="../static/img/bahiaHawai.jpg" alt="bahiaHawai">
    <div class="text">Hawai</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
<div class="card">
    <img src="../static/img/newYork.jpg" alt="bahiaHawai">
    <div class="text">New York</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
<div class="card">
    <img src="../static/img/Mauna_Kea.jpg" alt="bahiaHawai">
    <div class="text">Mauna Kea</div>
    <div class="enlace"><a href="{{ url_for('dashboard.dashboardpaquetes') }}">Ver Más+</a></div>
</div>
</div>
    
{% endblock %}

app/templates/dashboard/listareserva.html
{% extends 'layoutDashboard.html' %}

{% block content %}
<div class="container py-4">
  <h1 class="text-center mb-5 fw-bold text-primary">Mis reservas</h1>

  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for reserva in reservas %}
    <div class="col">
      <div class="card h-auto shadow rounded-4">
        <img src="{{ reserva[7] }}" class="card-img-top rounded-top-4" style="height: 200px; object-fit: cover;" alt="Imagen destino" >
        <div class="card-body p-4">
          <h5 class="card-title fw-bold text-primary">{{ reserva[3] }}</h5> <!-- destino -->
          <p class="card-text mb-1"><strong>Pasajero:</strong> {{ reserva[1] }}</p>
          <p class="card-text mb-1"><strong>Email:</strong> {{ reserva[2] }}</p>
          <p class="card-text mb-1"><strong>Fecha:</strong> {{ reserva[4] }}</p>
          <p class="card-text mb-1"><strong>Personas:</strong> {{ reserva[5] }}</p>
          <p class="card-text mb-1"><strong>Precio:</strong> ${{ reserva[6]|format_price }}</p>
        <form action="{{ url_for('dashboard.eliminar_reserva', id=reserva[0]) }}" method="POST" >
        <button type="submit" class="btn btn-outline-danger ">Eliminar</button>
        </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="text-center mt-5">
    <a href="{{ url_for('dashboard.dashboardreserva') }}" class="btn btn-primary">Volver</a>
  </div>
  
</div>
{% endblock %}

app/templates/dashboard/paquetes.html
{% extends 'layoutDashboard.html' %}
{% block content %}

<div class="paquetes_img">
    <img src="static/img/paq.webp" class="paquetes-img"" alt=" ...">
</div>

{% if paquetes %}
<div class="container">
    <div class="row">
        {% for paquete in paquetes %}

        <div class="col-md-4 mb-4">
            <div class="card-paquetes  rounded-4 shadow  shadow p-3">
                <div class="card-bodyp-3 d-flex flex-column">
                    <img src={{paquete.imagen}} class="card-img-top rounded-top-4" alt="cordoba">
        
                    <div class="trip-duration text-muted mt-3"> {{ paquete.duracion }} - {{ paquete.mes}}</div>
                    <h3 class="card-title mt-2">{{ paquete.destino }}</h3>
                    <div class="trip-options">
                        <span class="badge bg-secondary mt-1">{{ paquete.incluye | join(', ') }}</span>
                    </div>
                    <div class="price mt-1"> $ {{ paquete.precio_por_persona | format_price}}</div>
                    <div class="d-flex justify-content-between align-items-center mt-0">
                        <span class="badge bg-success">Disponible</span>
                       
                        <a href="{{ url_for('dashboard.dashboardreserva', paquete_id=paquete.id, destino=paquete.destino, duracion=paquete.duracion, precio=paquete.precio_por_persona) }}"
                            class="btn btn-primary rounded-4 px-4">
                        Reservar  
                        </a>
                    </div>

                </div> <!-- 5:card-body -->
            </div> <!-- 4:card-paquetes -->
        </div> <!-- 3: col-md-4 mb-4-->

        {% endfor %}
    </div> <!-- row-->
</div> <!-- container -->
{% else %}
<h1>no hay paquetes</h1>
{% endif %}
{% endblock %}

app/templates/dashboard/reserva.html
{% extends 'layoutDashboard.html' %}

{% block content %}

<h3 class="text-center text-primary fw-bold mb-20"> Generar reserva</h3>
<div class="container">
    
    <form  class="card-paquetes rounded-4 shadow mt-5" method="POST" action="{{ url_for('dashboard.dashboardreserva') }}">
        <input type="hidden" name="paquete_id" value="{{ paquete_id }}">
        <input type="text" name="nombre" placeholder="Nombre" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="text" name="telefono" placeholder="Teléfono" required>
        <input class="p-2 rounded-1" type="date" name="fecha_reserva" required>
        <input class="p-2 rounded-1" type="number" name="numero_personas" placeholder="Número de Personas" required>
        <button class="mt-3 rounded-1" type="submit" class="btn btn-primary">Confirmar reserva</button>
    </form>
    
</div>



<div class="text-center mt-2">
    <a href="{{ url_for('dashboard.dashboardlistareserva') }}" class="btn btn-primary"> Mis reservas</a>
</div>

{% endblock %}

app/templates/layoutDashboard.html
<!-- app/templates/layout.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> NineTravel </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="assets/img/logoCirculeBlanco.png">


</head>
<body>
    <header>
        <div class="navbar">
            <img id="LogoNineT" src="../static/img/logotex.png" alt="logo">
           <nav id="menu_list">
    <ul>
        <li><a href="{{ url_for('dashboard.dashboard') }}"><div class="bi bi-people"></div> <span class="icon_text">Nosotros</span></a></li>          
        <li><a href="{{ url_for('dashboard.dashboarddestinos') }}"><div class="bi bi-geo-alt"></div> <span class="icon_text">Destinos</span> </a></li>
        <li><a href="{{ url_for('dashboard.dashboardpaquetes') }}"><div class="bi bi-airplane"></div> <span class="icon_text">Paquetes</span></a></li>
        <li><a href="{{ url_for('dashboard.dashboardlistareserva') }}"><div class="bi bi-calendar-check"></div><span class="icon_text">Reserva</span></a></li>

        {% if session.get('username') %}
            <li>
                <a href="#">
                    <div class="bi bi-person-circle"></div>
                    <span class="icon_text">{{ session['username'] }}</span>
                </a>
            </li>
            <li>
                <a href="{{ url_for('auth.logout') }}">
                    <div class="bi bi-box-arrow-right"></div>
                    <span class="icon_text">Cerrar sesión</span>
                </a>
            </li>
        {% else %}
            <li><a href="{{ url_for('auth.register') }}"><div class="bi bi-person-plus"></div> <span class="icon_text">Registrarse</span></a></li>
            <li><a href="{{ url_for('auth.login') }}"> <div class="bi bi-box-arrow-in-right"></div><span class="icon_text">Login</span></a></li>
        {% endif %}
    </ul>
</nav>

        </div>
    </header>

    <div id="flash-container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message {{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <main>
        
    {% block content %}{% endblock %}
    
    </main>

    <footer>
    <div class="conteiner-footer">
        <p class="pie">
            <i class="bi bi-geo-alt"></i> <span> Av. Caseros 3040, Buenos Aires, Argentina.</span>
        </p>
        <p class="pie">
            <i class="bi bi-envelope-at"></i> <span> TravelNine@gmail.com </span>
        </p>
        <p class="pie">
            <i class="bi bi-telephone-inbound"></i> <span> 4250-7030 </span>
        </p>
        <p class="pie">
            <i class="bi bi-phone"></i> <span> +54 9 11 2044-5680 </span>
        </p>
    </div>

    <div class="text-center">
        <p>Seguinos para mas novedades! </p>
        <ul class="list-unstyled list-inline">
            <li>
                <a href="#" class="icono-foter"> <i class="fab fa-facebook"> </i> </a>
            </li>

            <li>
                <a href="#" class="icono-foter"> <i class="fab fa-twitter"> </i> </a>
            </li>

            <li>
                <a href="#" class="icono-foter"> <i class="fab fa-google-plus"> </i> </a>
            </li>

            <li>
                <a href="#" class="icono-foter"> <i class="fab fa-linkedin"> </i> </a>
            </li>

            <li>
                <a href="#" class="icono-foter"> <i class="fab fa-youtube"> </i> </a>
            </li>
        </ul>
    </div>

    <div class="text-center">
        <p> &copy; 2024 NineTravel Todos los derechos reservados. </p>
    </div>

    </footer>
</body>
<script src="../static/js/index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</html>